/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package csms.database.message.component;

import java.awt.Color;
import javax.swing.JTextArea;

/**
 *
 * @author msu-wone
 */
public class homeMessage extends javax.swing.JPanel {

    /**
     * Creates new form homeMessage
     */
    public homeMessage() {
        initComponents();
        
        Ddesc.setOpaque(false);
        Ddesc.setBackground(new Color(0, 0, 0, 0));
        Ddesc.setAlignmentX(JTextArea.CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatar = new csms.database.theme.ImageAvatar();
        name = new javax.swing.JLabel();
        Ddesc = new javax.swing.JLabel();
        Ddesc1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText("jLabel1");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 10, -1, -1));

        Ddesc.setText("jLabel1");
        add(Ddesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 30, 188, -1));

        Ddesc1.setText("jLabel1");
        add(Ddesc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 46, 188, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Ddesc;
    public javax.swing.JLabel Ddesc1;
    public csms.database.theme.ImageAvatar avatar;
    public javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
